version: '3.8'

services:
  catalog-api:
    build:
      context: ./src
      dockerfile: Catalog.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQL: Host=dbGames;Port=5432;Database=dbGames;Username=postgres;Password=yourpassword
    depends_on:
      - dbGames

  dbGames:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: dbGames
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: